### ISSUE TITLE
python stable does not work on pds-doi-service

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/roundup-action#18] opened 2020-11-24 15:10 UTC
**Describe the bug**
The error can be found in https://github.com/NASA-PDS/pds-doi-service/runs/1444380603?check_suite_focus=true

**To Reproduce**
Create a tag on pds-doi-service

**Comment by nutjob4life** [comment] 2020-11-30 18:41
I see the error message in the log file referenced above, but I don't think it's related to the Roundup Action. (This issue is labeled as a bug in the Roundup Action, but it seems to be environmental, perhaps similar to how `/bin/ls /non/existent` also gives an error message, but isn't a bug in `/bin/ls`? 🤷‍♀️)

Regardless, I'm unable to reproduce using the instructions given above. Here's what I did:

1. `git clone git@github.com:NASA-PDS/pds-doi-service.git`
2. `cd pds-doi-service`
3. `git tag -a -m 'Roundup testing; ignore' v9.8.7`
4. `git push origin v9.8.7`

This resulted in a successful roundup; see: https://github.com/NASA-PDS/pds-doi-service/runs/1475377400

Am I missing something? Please let me know. If this is truly a bug in the Roundup, I'd like to stamp it out 🤨

![Screen Shot 2020-11-30 at 12 37 08 PM](https://user-images.githubusercontent.com/814813/100649943-cc94f080-3308-11eb-8e32-e62fc718a46a.png)

**Comment by nutjob4life** [comment] 2020-12-02 21:14
For purposes of [milestone PDS.05](https://github.com/NASA-PDS/roundup-action/milestone/4) due 2020-12-02 (today) I recommend closing this with the resolution "unable to reproduce". Feel free to re-open in another sprint should it appear again.

**Closed by nutjob4life** 2020-12-02 21:14 UTC
Labels: bug

**Comment by tloubrieu-jpl** [comment] 2020-12-03 04:40
I was still reproducing the error but was able to overcome it by adding fetch-depth: 0 option to the checkout action. For example:

 steps:
            -
                name: 💳 Checkout
                uses: actions/checkout@v2
                with:
                    lfs: true
                    fetch-depth: 0

This might also have impacts, so I don't recommend to apply it always yet.
